spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    # properties:
    #   hibernate:
    #     format_sql: true

    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: TRACE