package com.ecom.ecommerce.constant;

public enum ErrorCode {
    PRODUCT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    USER_NOT_FOUND,
    ORDER_NOT_FOUND,
    ORDER_ITEM_NOT_FOUND,
    ADDRESS_NOT_FOUND,

    PRODUCT_ALREADY_EXISTS,
    CATEGORY_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,

    INVALID_REQUEST,
    VALIDATION_ERROR,

    UNAUTHORIZED,
    FORBIDDEN,

    INTERNAL_SERVER_ERROR
}